config/routes.rb
Rails.application.routes.draw do

  root 'pages#root_proxy'

  devise_for :employees

  get 'admin/reports/assistance' => 'timelogs#assistance'
  get 'admin/timelogs/reported_errors' => 'timelogs#reported_errors'
  put 'admin/timelogs/reported_errors/:id/update' => 'timelogs#reported_error_update', as: 'admin_timelogs_reported_error'
  
  resources :employees, only: [:show]
  resources :timelogs, only: [:index, :show, :edit, :update]

end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  belongs_to :employee

  CLAIM_STATUS_OPT = %w(pending approved declined)
  REPORT_TYPE_OPT = {tardies: 'Tardies', missed_work: 'Missed Work'}
  PAYROLL = {pay_day: 7, review_days_before_pay_day: 3}


  validates :employee_id,
    presence: true,
    numericality: {
      only_integer: true,
    },
    inclusion: {      
      in: :employee_ids
    }

  validates :log_date,
    presence: true,
    uniqueness: { 
      scope: :employee_id,
      message: "There can only be one timelog per date per employee" 
    }

  validate(
    :validate_arrive_sec,
    :validate_leave_sec,
    :validate_claim_leave_sec,
    :validate_claim_status
  )


  def self.get_correct_moment(moment, timelog) 
    time_col = "#{moment}_sec".to_sym
    claim_time_col = "claim_#{moment}_sec".to_sym
    time_recorded = timelog.send(time_col)
    time_claim = timelog.send(claim_time_col)
    status = timelog.send :claim_status

    res = time_claim ? time_claim : time_recorded
    res = time_recorded if status == 'declined'
    return res
  end

  def self.timelogs_for_index_view(timelogs, start_date, end_date) 
    period_minutes = 0
    logged_time = {}
    processed_timelogs = []

    current_date = start_date
    while current_date <= end_date
      hash = {}
      current_date += 1.day and next if [6,7].include? current_date.cwday # skip weekends
      hash[:log_date] = current_date.strftime '%a, %d-%b-%Y'

      unless timelog = timelogs.where(log_date: current_date).first
        hash[:arrive_time] = 'Missing'
        hash[:leave_time] = 'Missing'
        hash[:status] = 'Missed Day'
      else
        arrive = get_correct_moment(:arrive, timelog)
        leave = get_correct_moment(:leave, timelog)
        hash[:arrive_time] = 
          arrive ? (timelog.log_date + arrive.seconds).strftime('%l:%M %p') : 'Missing'
        hash[:leave_time] = 
          leave ? (timelog.log_date + leave.seconds).strftime('%l:%M %p') : 'Missing'

        seconds = (leave.nil? or arrive.nil?) ? 0 : (leave - arrive).to_i
        hash[:hours] = Util.seconds_to_hrs_min(seconds)[:hours]
        hash[:minutes] = Util.seconds_to_hrs_min(seconds)[:minutes]
        period_minutes += hash[:minutes] + hash[:hours] * 60
        
        case timelog.claim_status
        when 'pending'
          hash[:status] = 'Pending Review'
        when 'approved'
          hash[:status] = 'Claim Approved'
        when 'declined'
          hash[:status] = 'Claim Declined'
        end

        if Time.now.to_date + PAYROLL[:review_days_before_pay_day].days == self.get_pay_date(timelog)
        # if true
          link = self.new.edit_timelog_path(timelog.id)          
          hash[:action] = {}
          case timelog.claim_status
          when NilClass
            hash[:action][:text] = 'Report Error'
            hash[:action][:path] = link
          when 'pending'
            hash[:action][:text] = 'Edit Report' 
            hash[:action][:path] = link
          end
        end
      end

      processed_timelogs << hash
      current_date += 1.day
    end

    logged_time[:hours] = period_minutes / 60
    logged_time[:minutes] = period_minutes - logged_time[:hours] * 60
    return {timelogs: processed_timelogs, time: logged_time}
  end

  def self.get_pay_date(timelog) 
    Date.new(timelog.log_date.year, timelog.log_date.month, -1) + PAYROLL[:pay_day].days
  end

  private

    def employee_ids
      Employee.all.pluck(:employee_id)
    end

    def validate_arrive_sec 
      return if arrive_sec.nil?

      if arrive_sec > max_sec_in_day()
        errors.add(:arrive_sec, "The time entered is beyond an acceptable range.")
        return
      end
    end

    def validate_leave_sec 
      return if leave_sec.nil? or claim_leave_sec

      if leave_sec > max_sec_in_day()
        errors.add(:leave_sec, "The time entered is beyond an acceptable range.")
        return
      end

      if arrive_sec.nil? and claim_arrive_sec.nil?
        errors.add(:leave_sec, "Arrive time cannot be blank if Leave time has data.")
        return
      end

      arrive = claim_arrive_sec ? claim_arrive_sec : arrive_sec
      if leave_sec < arrive
        errors.add(:leave_sec, "The Departure cannot happen before the Arrival")
        return
      end
    end

    def validate_claim_leave_sec 
      return if claim_leave_sec.nil?

      if arrive_sec.nil? and claim_arrive_sec.nil?
        errors.add(:claim_leave_sec, "Arrive time cannot be blank if Leave time has data.")
        return
      end

      arrive = claim_arrive_sec ? claim_arrive_sec : arrive_sec
      if claim_leave_sec < arrive
        errors.add(:claim_leave_sec, "The Departure cannot happen before the Arrival")
        return
      end
    end

    def max_sec_in_day 
      24.hours - 1.second
    end

    def validate_claim_status 
      if claim_status.nil? and (claim_arrive_sec or claim_arrive_sec)
        errors.add(:claim_status, "A Status must be entered if there is a Claim")
        return
      end

      return if claim_status.nil?

      unless CLAIM_STATUS_OPT.include? claim_status
        errors.add(:claim_status, "The claimed status entered is invalid.")
      end    
    end

end

app/controllers/timelogs_controller.rb
class TimelogsController < ApplicationController
  before_action :set_timelog, only: [:edit, :show, :update]
  before_action :authorize_employee, only: [:assistance, :reported_errors, :reported_error_update]

  # GET /timelogs
  # GET /timelogs.json
  def index
    today = Time.now.to_date
    timeframe_start = today - 4.months
    timeframe_start = Date.new timeframe_start.year, timeframe_start.month
    timeframe_end = Date.new today.year, today.month, -1
    
    @timelogs = Timelog.where(
      'employee_id = ? AND log_date >= ? AND log_date <= ?',
      current_employee.id, timeframe_start, timeframe_end
    ).order(log_date: :desc)
    
    @periods = {collection: [], active: nil}
    period_start = timeframe_start
    period_end = Date.new period_start.year, period_start.month, -1
    while period_start <= timeframe_end
      period = period_start.strftime('%d/%b/%Y') + ' –– ' +  period_end.strftime('%d/%b/%Y')
      @periods[:collection] << [period, period_start]
      period_start = period_end + 1.day
      period_end = Date.new period_start.year, period_start.month, -1
    end
    @periods[:active] = params.fetch(:timelogs, {}).fetch(:period, @periods[:collection].last[1].to_s)

    view_start_date = Date.parse @periods[:active]
    view_end_date = Date.new view_start_date.year, view_start_date.month, -1
    timelogs_data = Timelog.timelogs_for_index_view(@timelogs, view_start_date, view_end_date)
    @timelogs_time = timelogs_data[:time]
    @proc_timelogs = timelogs_data[:timelogs]
  end

  # GET /timelogs/1
  # GET /timelogs/1.json
  def show
    @period = print_pay_timeframe(@timelog.log_date, @timelog.log_date).first
  end

  # GET /timelogs/new
  def new
    # disabled in routes
  end

  # GET /timelogs/1/edit
  def edit
    if @timelog.claim_status == 'approved'
      alert = 'The action attempted cannot be completed.'
      redirect_to(timelogs_path, alert: alert) and return
    end
    @period = print_pay_timeframe(@timelog.log_date, @timelog.log_date).first
  end

  # POST /timelogs
  # POST /timelogs.json
  def create
    # disabled in routes
    @timelog = Timelog.new(timelog_params)

    respond_to do |format|
      if @timelog.save
        format.html { redirect_to @timelog, notice: 'Timelog was successfully created.' }
        format.json { render :show, status: :created, location: @timelog }
      else
        format.html { render :new }
        format.json { render json: @timelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelogs/1
  # PATCH/PUT /timelogs/1.json
  def update
    tl_updates = {}
    timelog_params.each do |k, v|
      v.strip!
      moment = %w(arrive leave).select{|x| k.include? x}[0]

      if v.empty?
        tl_updates["claim_#{moment}_sec"] = nil
      else
        dt = DateTime.parse "#{@timelog.log_date} #{v}"
        seconds_difference = dt.to_i - @timelog.log_date.to_datetime.to_i
        tl_updates["claim_#{moment}_sec"] = seconds_difference
        tl_updates[:claim_status] = 'pending'
      end
    end
    @timelog.update!(tl_updates)

    notice = 'Report successfully submitted.'
    redirect_to timelog_path(@timelog), notice: notice
  rescue Exception => e
    flash[:alert] = 'Invalid time format entered. Please follow the pattern "5:35 pm".'
    render :edit
  end

  # DELETE /timelogs/1
  # DELETE /timelogs/1.json
  def destroy
    # disabled in routes
    @timelog.destroy
    respond_to do |format|
      format.html { redirect_to timelogs_url, notice: 'Timelog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /timelogs/assistance
  def assistance 
    today = Time.now.to_date
    @report_q = {}
    @report_q[:start_date] = Date.parse params[:start_date] ? params[:start_date] : (today - 60.days).to_s
    @report_q[:end_date] = Date.parse params[:end_date] ? params[:end_date] : today.to_s
    report_type_opt = Timelog::REPORT_TYPE_OPT.keys.map{|x| x.to_s}
    @report_q[:type] = report_type_opt.include?(params[:type]) ? params[:type] : report_type_opt.first
    run_report = {
      tardies: 'timelogs_tardies(@report_q[:start_date], @report_q[:end_date])', 
      missed_work: 'timelogs_missed_work(@report_q[:start_date], @report_q[:end_date])'
    }

    @timelogs = eval(run_report[@report_q[:type].to_sym])

    @report_q[:chart_all] = Timelog
      .where('log_date >= ? AND log_date <= ?', @report_q[:start_date], @report_q[:end_date])
      .count
    @report_q[:chart_part] = @timelogs.count
    @report_q[:chart_label_all] = @report_q[:type] == 'tardies' ? 'On Time' : 'Worked'
    @report_q[:chart_label_part] = @report_q[:type] == 'tardies' ? 'Late' : 'Missed Work'
  rescue Exception => e
    notice = 'There was an error processing the report.'
    redirect_to assistance_url, notice: notice
  end

  # GET /reported_errors
  def reported_errors 
    start_date = Time.now.to_date - 3.months
    end_date = Time.now.to_date

    @timelogs = Timelog
      .where('(claim_status = ?) OR (log_date >= ? AND log_date <= ? AND claim_status IN (?))',
        'pending', start_date, end_date, ['approved', 'declined'])
      .order(log_date: :asc)
  end

  # PUT /reported_errors/:id/udpate
  def reported_error_update 
    possible_statuses = %w(pending approved declined)
    timelog = Timelog.where(id: params[:id]).first
    new_status = params[:claim_status]

    timelog = timelog.claim_status.nil? ? nil : timelog
    new_status = possible_statuses.include?(new_status) ? new_status : nil
    redirect_to(admin_timelogs_reported_errors_path) and return if timelog.nil? or new_status.nil?

    timelog.update claim_status: new_status
    redirect_to admin_timelogs_reported_errors_path, notice: "Timelog successfully updated."
  rescue Exception => e
    redirect_to admin_timelogs_reported_errors_path, alert: "There was an error processig your request."
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def timelog_params
      params.require(:timelog).permit(:claim_arrive_sec, :claim_leave_sec)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_timelog
      @timelog = Timelog.where(id: params[:id]).first

      if @timelog.nil?
        notice = 'The Timelog searched could not be found.'
        redirect_to(timelogs_path, notice: notice) and return
      end

      if @timelog.employee_id != current_employee.id
        notice = 'You attempted an unauthorized action.'
        redirect_to timelogs_path, notice: notice
      end
    end

    def timelogs_date_range(start_date, end_date) 
      Timelog.where('log_date >= ? AND log_date <= ?',start_date, end_date)
        .order(log_date: :asc)
    end

    def timelogs_tardies(start_date, end_date) 
      timelogs_date_range(start_date, end_date)
        .select do |t|
          if t.arrive_sec.nil? and t.claim_arrive_sec.nil?
            false
          else
            case t.claim_status
            when 'pending', 'approved'
              9.hours < (t.claim_arrive_sec ? t.claim_arrive_sec : t.arrive_sec)
            when 'declined', NilClass
              9.hours < t.arrive_sec
            end
          end
        end
    end

    def timelogs_missed_work(start_date, end_date) 
      missed_work = []
      timelogs = Timelog.where('log_date >= ? AND log_date <= ?', start_date, end_date)

      Employee.all.each do |employee|
        date = start_date
        while date <= end_date
          date += 1 and next if [6,7].include? date.cwday # skip weekends        
          unless timelogs.where(employee: employee, log_date: date).any?
            fake_timelog = Struct.new(:log_date, :employee, :arrive_sec, :leave_sec, :claim_arrive_sec, :claim_leave_sec, :claim_status).new
            fake_timelog.log_date = date
            fake_timelog.employee = employee
            missed_work << fake_timelog
          end
          date += 1.day
        end
      end

      return missed_work
    end

    def print_pay_timeframe(start_date, end_date) 
      period_start = start_date
      period_end = Date.new period_start.year, period_start.month, -1
      periods = []
      while period_start <= end_date
        periods << period_start.strftime('%d/%b/%Y') + ' –– ' +  period_end.strftime('%d/%b/%Y')
        period_start = period_end + 1.day
        period_end = Date.new period_start.year, period_start.month, -1
      end

      return periods
    end

end

app/helpers/timelogs_helper.rb
module TimelogsHelper

  def timelog_moment_in_time(moment, timelog) 
    moment_i = Timelog.get_correct_moment(moment, timelog)
    res = moment_i ? (DateTime.new(2016) + moment_i.seconds).strftime('%l:%M %p') : 'Missing'
    return res
  end

  def moment_as_time_for_edit(moment, if_nil) 
    res = moment ? (DateTime.new(2016) + moment.seconds).strftime('%l:%M %p') : if_nil
    return res
  end

  def print_late_by(arrive_time, timelog) 
    correct_arrive_sec = (timelog.log_date.to_datetime + arrive_time).to_i - timelog.log_date.to_datetime.to_i
    res = 'N/A'

    if arrive_sec = Timelog.get_correct_moment(:arrive, timelog)
      sec_diff = arrive_sec ? (arrive_sec - correct_arrive_sec) : 0
      res = sec_diff > 0 ? "#{sec_diff / 60} minutes" : nil
    end

    return res
  end

  def reported_error_action(timelog) 
    case timelog.claim_status
    when 'pending'
      approve = link_to 'Approve', 
        admin_timelogs_reported_error_path(timelog.id, claim_status: 'approved'),
        method: :put, id: "#{timelog.id}_approve"
      decline = link_to 'Decline', 
        admin_timelogs_reported_error_path(timelog.id, claim_status: 'declined'),
        method: :put, id: "#{timelog.id}_decline"
      return "#{approve} / #{decline}".html_safe
    when 'approved'
      link_to 'Change to Decline', 
        admin_timelogs_reported_error_path(timelog.id, claim_status: 'declined'),
        method: :put, id: "#{timelog.id}_change_to_decline"
    when 'declined'
      link_to 'Change to Approve', 
        admin_timelogs_reported_error_path(timelog.id, claim_status: 'approved'),
        method: :put, id: "#{timelog.id}_change_to_approve"
    end
  end

  def tr_report_error_class(timelog) 
    klass = nil
    klass = 'timelog-status-approved' if timelog.claim_status == 'approved'
    klass = 'timelog-status-declined' if timelog.claim_status == 'declined'
    
    return klass
  end

end

app/views/timelogs/_form.html.haml
= form_for @timelog do |f|
  %p
    %strong Timelog ID:
    = @timelog.id

  %table
    %thead
      %th Moment
      %th Reported
      %th 
        = 'Claimed by Employee'
        %br/
        %span (ex: 5:35 pm)
    %tbody
      %tr
        %td Arrival
        %td= moment_as_time_for_edit(@timelog.arrive_sec, 'Missed')
        %td= f.text_field :claim_arrive_sec, value: moment_as_time_for_edit(@timelog.claim_arrive_sec, nil)
      %tr
        %td Departure
        %td= moment_as_time_for_edit(@timelog.leave_sec, 'Missed')
        %td= f.text_field :claim_leave_sec, value: moment_as_time_for_edit(@timelog.claim_leave_sec, nil)

  .actions
    = f.submit 'Submit', class: 'button'
    = link_to 'Cancel', timelogs_path, class: 'float-right button warning'

app/views/timelogs/assistance.html.haml
= render './top_menu'
#timelogs-assistance
  .row
    .column.medium-12
      %h2.page-title.text-center Assistance Reports
    .column.large-offset-1.large-4
      = form_tag admin_reports_assistance_path, method: :get, id: 'report-params'
      %table
        %tr
          %td= label_tag :type, 'Report Type'
          %td= select_tag :type,
            options_for_select(Timelog::REPORT_TYPE_OPT.map{|k,v| [v, k]}, @report_q[:type])
        %tr
          %td= label_tag :start_date, 'Start Date'
          %td
            .subheader format: dd/mm/yyyy
            = date_field_tag :start_date, @report_q[:start_date]
        %tr
          %td= label_tag :end_date, 'End Date'
          %td
            .subheader format: dd/mm/yyyy
            = date_field_tag :end_date, @report_q[:end_date]
      .row
        .column.large-12.text-center
          = submit_tag 'Send Parameters', class: 'button text-center'
    .column.large-7
      = pie_chart({@report_q[:chart_label_all] => @report_q[:chart_all],
        @report_q[:chart_label_part] => @report_q[:chart_part]}, colors: ['#DFA584', "#999"])
  .row
    .column.large-12
      %table
        %thead
          %th
          %th Date
          %th Employee ID
          %th Name
          %th Arrival
          %th Departure
          %th Late By
        %tbody
          - if @timelogs.empty?
            %tr
              %td{colpan: 5} There is no data to display.
          - else
            - index = 0
            - @timelogs.each do |timelog|
              %tr
                %td= index += 1
                %td= strftime_as_date(timelog.log_date)
                %td= timelog.employee.id
                %td= timelog.employee.full_name
                %td= timelog_moment_in_time(:arrive, timelog)
                %td= timelog_moment_in_time(:leave, timelog)
                %td= print_late_by(9.hours, timelog)

app/views/timelogs/edit.html.haml
= render './top_menu'
#timelogs_edit
  .row
    .column.medium-12
      %h2.page-title.text-center Report Timesheet Error

      .column.small-10.small-offset-1.medium-6.medium-offset-3.large-4.large-offset-4.end
        %p
          %strong Employee:
          = @timelog.employee.full_name
        - if @period
          %p
            %strong Pay Period:
            = @period
        %p
          %strong Date Disputed:
          = @timelog.log_date.strftime '%a, %d-%b-%Y'

        %p
          %strong Claim Status:
          = @timelog.claim_status ? @timelog.claim_status.titlecase : nil

      .column.medium-8.medium-offset-2.end
        %br/
        = render 'form'

app/views/timelogs/index.html.haml
= render './top_menu'
#timelogs_index
  .row
    .column.small-12
      %h2.page-title.text-center Timesheet Review
    .column.small-8.small-offset-2.medium-4.medium-offset-4.end
      %p
        %strong Name:
        = current_employee.full_name
      %p
        = form_for 'timelogs', method: :get do |f|
          %strong Pay Period:
          = f.select :period, @periods[:collection], selected: @periods[:active]
          = f.submit 'Submit', class: 'button'
    .column.large-12
      %p
        %strong Time Reported:
        - unless @timelogs_time.empty?
          = "#{@timelogs_time[:hours]} hours, #{@timelogs_time[:minutes]} minutes"
      %br/
      %table.highlight-hover-row
        %thead
          %th Date
          %th Arrival
          %th Departure
          %th Hours
          %th Minutes
          %th Status
          %th Actions
        %tbody
          - if @proc_timelogs.empty?
            %tr
              %td{colspan: 7} There is no data for this period.
          - else
            - @proc_timelogs.each do |timelog|
              %tr
                %td= timelog[:log_date]
                %td= timelog[:arrive_time]
                %td= timelog[:leave_time]
                %td= timelog[:hours]
                %td= timelog[:minutes]
                %td= timelog[:status]
                %td
                  -if timelog[:action] and timelog[:action].any?
                    = link_to(timelog[:action][:text], timelog[:action][:path])

app/views/timelogs/new.html.haml
%h1 New timelog

= render 'form'

= link_to 'Back', timelogs_path

app/views/timelogs/reported_errors.html.haml
= render './top_menu'
#timelogs-reported-errors
  .row
    .column.medium-12
      %h2.page-title.text-center Reported Timesheet Errors

    .column.large-12
      %br/
      %table.highlight-hover-row
        %thead
          %th Date
          %th ID
          %th Name
          %th Arrival
          %th Claimed Arrival
          %th Departure
          %th Claimed Departure
          %th Claim Status
          %th Actions
        %tbody
          - @timelogs.each do |timelog|
            %tr{class: tr_report_error_class(timelog)}
              %td= strftime_as_date(timelog.log_date)
              %td= timelog.employee.id
              %td= timelog.employee.full_name
              %td= moment_as_time_for_edit(timelog.arrive_sec, nil)
              %td= moment_as_time_for_edit(timelog.claim_arrive_sec, nil)
              %td= moment_as_time_for_edit(timelog.leave_sec, nil)
              %td= moment_as_time_for_edit(timelog.claim_leave_sec, nil)
              %td= timelog.claim_status.titlecase
              %td= reported_error_action(timelog)

app/views/timelogs/show.html.haml
= render './top_menu'
#timelogs_edit
  .row
    .column.medium-12
      %h2.page-title.text-center Reported Timesheet Error

      .column.small-10.small-offset-1.medium-6.medium-offset-3.large-4.large-offset-4.end
        %p
          %strong Employee:
          = @timelog.employee.full_name
        - if @period
          %p
            %strong Pay Period:
            = @period
        %p
          %strong Date Disputed:
          = @timelog.log_date.strftime '%a, %d-%b-%Y'

        %p
          %strong Claim Status:
          = @timelog.claim_status ? @timelog.claim_status.titlecase : nil

      .column.medium-8.medium-offset-2.end
        %br/

        %p
          %strong Timelog ID:
          = @timelog.id

        %table
          %thead
            %th Moment
            %th Reported
            %th 
              = 'Claimed by Employee'
          %tbody
            %tr
              %td Arrival
              %td= moment_as_time_for_edit(@timelog.arrive_sec, 'Missed',)
              %td= moment_as_time_for_edit(@timelog.claim_arrive_sec, nil,)
            %tr
              %td Departure
              %td= moment_as_time_for_edit(@timelog.leave_sec, 'Missed',)
              %td= moment_as_time_for_edit(@timelog.claim_leave_sec, nil,)

        .actions
          = link_to 'Timesheets', timelogs_path, class: 'button'
          = link_to 'Edit Report', edit_timelog_path(@timelog), class: 'float-right button'